name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs every 24 hours
  workflow_dispatch:     # allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake game from GitHub contributions
        uses: Platane/snk@v3
        with:
          github_user_name: Luvin-2511  # <-- change to your username
          outputs: dist/snake.svg

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
